scan_timeout = 10
add_newline = false

format = "$directory $cmd_duration$character"

[character]
success_symbol = "ïŒƒ"
error_symbol =   "[ïŒƒ](bold red)"

[cmd_duration]
min_time = 1000
format = "[ï¨$duration](bold purple) "

[package]
disabled = true

#[username]
#format = "[î› $user](dimmed) "
#disabled = false
#show_always = true

#[battery]
#full_symbol = "ğŸ”‹ "
#charging_symbol = "âš¡ï¸ "
#discharging_symbol = "ğŸ’€ "
#
#[[battery.display]]
#threshold = 10
#style = "bold red"

[directory]
truncation_length = 5
format = "[î—¾ $path]($style)[$lock_symbol]($lock_style)"
style = "bold italic blue"